name: Build tail (weather+time)
on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci || npm i

      - name: Lag tail (vær + klokke)
        run: node scripts/build_tail.js
        env:
          ELEVENLABS_API_KEY:  ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          LANGUAGE_PRIMER:     ${{ secrets.LANGUAGE_PRIMER }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SKILBREI_LAT:        ${{ secrets.SKILBREI_LAT }}
          SKILBREI_LON:        ${{ secrets.SKILBREI_LON }}

      - name: Prepare Pages artifact
        run: |
          mkdir -p public
          # publiser begge så Homey alltid finn dei
          [ -f velkomst_intro.mp3 ] && cp velkomst_intro.mp3 public/
          cp velkomst_tail.mp3 public/

      - uses: actions/upload-pages-artifact@v3
        with: { path: public }

      - uses: actions/deploy-pages@v4
