name: Build tail (weather+time)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    env:
      TZ: Europe/Oslo
      PAGES_BASE: https://bassdalsky.github.io/ALTVIRKER

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      # Hent gjeldende intro fra Pages slik at den ikke forsvinner ved ny deploy
      - name: Fetch existing intro from Pages (best effort)
        run: |
          curl -fL --retry 3 --connect-timeout 10 \
            "$PAGES_BASE/velkomst_intro.mp3" \
            -o velkomst_intro.mp3 || echo "No existing intro on Pages (ok)"

      - name: Build tail (weather+clock)
        run: node scripts/build_tail.js
        env:
          ELEVENLABS_API_KEY:  ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          LANGUAGE_PRIMER:     ${{ secrets.LANGUAGE_PRIMER }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SKILBREI_LAT:        ${{ secrets.SKILBREI_LAT }}
          SKILBREI_LON:        ${{ secrets.SKILBREI_LON }}

      - name: Prepare Pages artifact
        run: |
          mkdir -p public
          # Behold intro hvis vi fant den
          [ -f velkomst_intro.mp3 ] && cp velkomst_intro.mp3 public/
          # Legg alltid med ny hale
          cp velkomst_tail.mp3 public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
