name: Render & publish (velkomst + godkveld)

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build velkomst.mp3
        run: node scripts/velkomst.js > velkomst.mp3
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SKILBREI_LAT: ${{ secrets.SKILBREI_LAT }}
          SKILBREI_LON: ${{ secrets.SKILBREI_LON }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          LANGUAGE_PRIMER: ${{ secrets.LANGUAGE_PRIMER }}
          JULEMODUS: ${{ secrets.JULEMODUS }}

      - name: Build godkveld.mp3
        run: node scripts/godkveld.js > godkveld.mp3
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SKILBREI_LAT: ${{ secrets.SKILBREI_LAT }}
          SKILBREI_LON: ${{ secrets.SKILBREI_LON }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          LANGUAGE_PRIMER: ${{ secrets.LANGUAGE_PRIMER }}
          JULEMODUS: ${{ secrets.JULEMODUS }}

      - name: Prepare public folder
        run: |
          mkdir -p public
          cp velkomst.mp3 public/velkomst.mp3
          cp godkveld.mp3 public/godkveld.mp3
          ls -lh public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
