name: Render intro (once)
on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # ✅ VIKTIG: Pages trenger environment=github-pages
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci || npm i

      - name: Lag ny intro
        run: node scripts/make_intro_now.js
        env:
          ELEVENLABS_API_KEY:  ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          LANGUAGE_PRIMER:     ${{ secrets.LANGUAGE_PRIMER }}

      - name: Prepare Pages artifact
        run: |
          mkdir -p public
          cp velkomst_intro.mp3 public/ || true

      - uses: actions/upload-pages-artifact@v3
        with: { path: public }

      - name: Deploy to GitHub Pages
        id: deploy      # ✅ gir URL-output
        uses: actions/deploy-pages@v4
