name: Velkomst (bygg)

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [velkomst-full]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install (no deps, but keep ci step)
        run: npm ci || true

      - name: Bygg velkomst.mp3
        run: npm run velkomst
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          ELEVENLABS_API_KEY:  ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          SKILBREI_LAT:        ${{ secrets.SKILBREI_LAT }}
          SKILBREI_LON:        ${{ secrets.SKILBREI_LON }}
          JULEMODUS:           ${{ secrets.JULEMODUS }}

      - name: Prepare artifact
        run: |
          mkdir -p public
          cp velkomst.mp3 public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
