name: velkomst-intro-setup-jul

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v4

      - name: Sett opp Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installer avhengigheter
        run: npm install node-fetch@3

      - name: Generer jule-introar
        run: node intro_setup.js
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          VOICE_LABELS: Olaf,Mia,Emma
          LANGUAGE_PRIMER: ${{ secrets.LANGUAGE_PRIMER }}
          INTRO_FILE: meldinger_jul.txt
          INTRO_DIR: intros_xmas

      - name: Commit og push jule-introfiler
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add intros_xmas/*.mp3
          git commit -m "Oppdatert jule-introer" || echo "Ingen endringer"
          git push
