name: Render & publish (full)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "1 0 * * *"   # 00:01 UTC (01:01/02:01 lokalt)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-publish:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Render velkomst (mp3)
        run: npm run velkomst
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          ELEVENLABS_API_KEY:  ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          SKILBREI_LAT:        ${{ secrets.SKILBREI_LAT }}
          SKILBREI_LON:        ${{ secrets.SKILBREI_LON }}
          JULEMODUS:           ${{ secrets.JULEMODUS }}
          TIMEZONE:            ${{ secrets.TIMEZONE }}

      - name: Render godkveld (mp3)
        run: npm run godkveld
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          ELEVENLABS_API_KEY:  ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          SKILBREI_LAT:        ${{ secrets.SKILBREI_LAT }}
          SKILBREI_LON:        ${{ secrets.SKILBREI_LON }}
          JULEMODUS:           ${{ secrets.JULEMODUS }}
          TIMEZONE:            ${{ secrets.TIMEZONE }}

      - name: Prepare Pages artifact
        run: |
          mkdir -p public
          [ -f velkomst.mp3 ] && cp velkomst.mp3 public/
          [ -f godkveld.mp3 ] && cp godkveld.mp3 public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
