name: Velkomst (manuell test)
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut repo (rent)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Sett opp Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer avhengigheter
        run: npm install node-fetch@3

      - name: Generer velkomst.mp3
        run: node velkomst_bryter.js
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_IDS: ${{ secrets.ELEVENLABS_VOICE_IDS }}
          LANGUAGE_PRIMER: ${{ secrets.LANGUAGE_PRIMER }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SKILBREI_LAT: ${{ secrets.SKILBREI_LAT }}
          SKILBREI_LON: ${{ secrets.SKILBREI_LON }}

      - name: Commit og push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add velkomst.mp3
          git commit -m "Oppdatert velkomst.mp3 (manuell test)" || echo "Ingen endringer"
          git push

      - name: Varsle Homey (Velkomst)
        env:
          HOMEY_WEBHOOK_URL: ${{ secrets.HOMEY_WEBHOOK_URL }}
        run: |
          if [ -n "$HOMEY_WEBHOOK_URL" ]; then
            echo "Kaller Homey velkomst-webhook..."
            curl -sS -X POST "$HOMEY_WEBHOOK_URL"
          else
            echo "HOMEY_WEBHOOK_URL ikke satt — hopper over ping."
          fi
